/**
 * Master visual DNA prefix for Teddy Exteriors image generation.
 * Every architectural / editorial generation inherits this prefix.
 * See docs/teddy-homepage-transformation/VISUAL_ASSET_PLAN.md.
 */

export const MASTER_VISUAL_DNA = `
High-end editorial architectural photography of a realistic Pacific Northwest residence
appropriate to Vancouver, Washington and Portland, Oregon. Sophisticated but attainable
residential architecture, mature evergreen vegetation, natural Northwest landscaping,
soft diffused overcast daylight, subtle post-rain freshness, restrained charcoal + warm
white + stone + natural cedar material palette, physically believable construction details,
accurate architectural geometry, realistic siding, windows, fascia, soffit and roof
drainage, premium residential photography, natural dynamic range, straight verticals,
no HDR appearance, no fantasy architecture, no people posing, no vehicles dominating
the frame, no text, no logos, no watermarks.
`.trim();

export const NEGATIVE_CONSTRAINTS = [
  "McMansion", "Mediterranean villa", "palm trees", "desert landscaping", "Florida architecture",
  "California stucco estate", "European castle", "ultra-modern concrete compound",
  "billionaire mansion", "swimming pool", "Lamborghini", "fake contractor", "hard hat",
  "person pointing at wall", "stock-photo handshake", "extreme sunset", "artificial lens flare",
  "excessive bokeh", "HDR", "oversaturation", "fantasy weather", "fake signage",
  "text generated inside image", "company logo generated by model", "impossible building details",
  "fir-tree icon", "mountain silhouette pasted behind house",
].join(", ");

export type GenerationBrief = {
  id: string;
  role: "hero" | "service" | "material" | "regional" | "envelope" | "resource";
  aspect: `${number}:${number}`;
  mobileAspect?: `${number}:${number}`;
  focalPoint?: { x: number; y: number };
  safeArea?: string;
  lighting: string;
  materialPalette: string[];
  conversionFunction: "aspiration" | "proof" | "education" | "trust" | "regional";
  compositionNotes: string;
  specificSubject: string;
};

export function compilePrompt(brief: GenerationBrief): string {
  return [
    MASTER_VISUAL_DNA,
    "",
    `Role: ${brief.role}. Conversion function: ${brief.conversionFunction}.`,
    `Subject: ${brief.specificSubject}`,
    `Lighting: ${brief.lighting}.`,
    `Material palette: ${brief.materialPalette.join(", ")}.`,
    `Composition: ${brief.compositionNotes}. Aspect ratio ${brief.aspect}.`,
    brief.safeArea ? `Safe area for UI overlay: ${brief.safeArea}.` : "",
    "",
    `Avoid: ${NEGATIVE_CONSTRAINTS}.`,
  ]
    .filter(Boolean)
    .join("\n");
}
